repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --all
        language: system
        types: [rust]
        pass_filenames: false
      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy --all-targets --all-features -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false
      - id: prettier
        name: prettier
        entry: prettier --write
        language: system
        types_or: [markdown, yaml]
      - id: taplo
        name: taplo
        entry: taplo format
        language: system
        types: [toml]
      - id: nixfmt
        name: nixfmt
        entry: nixfmt
        language: system
        types: [nix]
