[book]
authors = ["Sven Over"]
language = "en"
multilingual = false
src = "docs"
title = "spr Documentation"

[build]
build-dir = "book"

[output.html]
git-repository-url = "https://github.com/spacedentist/spr"
edit-url-template = "https://github.com/spacedentist/spr/edit/master/{path}"
site-url = "/spr/"
curly-quotes = true
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"
