name: Build and deploy spr documentation

concurrency:
  group: gh-pages

on:
  push:
    branches:
      - master
    paths:
      - "book.toml"
      - "docs/**"

env:
  MDBOOK_VERSION: 0.5.4
  MDBOOK_MERMAID_VERSION: 0.17.1

jobs:
  mdbook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache mdbook
        id: cache-mdbook
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/mdbook
            ~/.cargo/bin/mdbook-mermaid
          key: ${{ runner.os }}-mdbook-${{ env.MDBOOK_VERSION }}-mermaid-${{ env.MDBOOK_MERMAID_VERSION }}

      - name: Install mdBook
        if: steps.cache-mdbook.outputs.cache-hit != 'true'
        run: |
          cargo install mdbook --version "$MDBOOK_VERSION" --locked
          cargo install mdbook-mermaid --version "$MDBOOK_MERMAID_VERSION" --locked

      - name: Run mdBook
        run: |
          mdbook-mermaid install
          mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
          publish_branch: gh-pages
