on: push
name: Clippy check

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        run: cargo clippy --all-targets --all-features

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        run: cargo test
