name: "Lint, format, test"

on:
  push:
    branches: [master]
  pull_request:

permissions:
  contents: read

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Linter
        id: lint
        if: "!cancelled()"
        run: cargo clippy --all-targets --all-features

      - name: Code formatter
        id: format
        if: "!cancelled()"
        run: cargo fmt --check

      - name: Tests
        id: test
        if: "!cancelled()"
        run: cargo test --all-features
